apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: python:3.6-alpine
          command: [
            "sh",
            "-c",
            "echo 'PÃ¡gina creada desde Python' > index.html && python -m http.server 8080"
          ]