apiVersion: v1
kind: Service
metadata:
  name: appointment-co-svc
spec:
  type: ClusterIP
  selector:
    app: appointment-co-app
  ports:
    - port: 80
      targetPort: 4020
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-co-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-co-app
  template:
    metadata:
      labels:
        app: appointment-co-app
    spec:
      containers:
        - name: appointment-co
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment-co
          imagePullPolicy: Always
          ports:
            - containerPort: 4020
          env:
            - name: PORT
              value: "4020"
            - name: DB_HOST
              value: "database-1.cmuv7any6zxa.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "Elgigante2025"
            - name: DB_NAME
              value: "appointment"
            - name: DB_SYNC
              value: "true"
            - name: DB_LOGG
              value: "true"
            - name: DB_POOL_SIZE
              value: "10"
            - name: KAFKA_BROKER
              value: "kafka-svc:29092"
            - name: KAFKA_TOPIC_CO
              value: appointment-topic-co
            - name: KAFKA_TOPIC_CONFIRM
              value: appointment-topic-confirm
            - name: KAFKA_TOPIC_ERROR
              value: appointment-topic-error
            - name: KAFKA_GROUP_ID
              value: "2000"
            - name: CLIENT_ID
              value: client-appointment
