apiVersion: v1
kind: Service
metadata:
  name: appointment-svc
spec:
  type: ClusterIP
  selector:
    app: appointment-app
  ports:
    - port: 4100
      targetPort: 4100
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-app
  template:
    metadata:
      labels:
        app: appointment-app
    spec:
      containers:
        - name: appointment
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/appointment
          resources:
            limits:
              cpu: 0.5
              memory: "200Mi"
            requests:
              cpu: 0.5
              memory: "100Mi"            
          imagePullPolicy: Always
          ports:
            - containerPort: 4100
          env:
            - name: NAME
              value: "appointment"
            - name: PORT
              value: "4100"
            - name: HOST
              value: "http://appointment-svc"
            - name: DB_HOST
              value: "database-1.cmuv7any6zxa.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "appuser"
            - name: DB_PASSWORD
              value: "apppassword"
            - name: DB_NAME
              value: "appointments_db"
            - name: DB_SYNCHRONIZE
              value: "true"
            - name: DB_LOGGING
              value: "false"
            - name: DB_POOL_SIZE
              value: "10"
            - name: DISCOVERY_URL
              value: "http://discovery-svc"
            - name: DISCOVERY_PORT
              value: "4000"
            - name: RABBITMQ_URL
              value: "amqp://localhost"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_PREFETCH
              value: "10"
            - name: RABBITMQ_EXCHANGE_NAME
              value: "appointments_exchange"
            - name: RABBITMQ_EXCHANGE_TYPE
              value: "direct"
            - name: RABBITMQ_QUEUE_APPOINTMENTS
              value: "appointments_queue"
            - name: RABBITMQ_ROUTING_KEY_APPOINTMENT
              value: "appointment_routing_key"
            - name: KAFKA_BROKER
              value: "kafka-svc:29092"
            - name: KAFKA_GROUP_ID
              value: "1000"
            - name: KAFKA_TOPIC
              value: "appointments_topic"
            - name: KAFKA_CLIENT_ID
              value: "appointment_service"
            - name: KAFKA_TOPIC_UPDATE
              value: "appointment_updates_topic"
