apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - port: 4700
      targetPort: 4700
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/auth
          resources:
            limits:
              cpu: 0.5
              memory: "200Mi"
            requests:
              cpu: 0.5
              memory: "100Mi"            
          imagePullPolicy: Always
          ports:
            - containerPort: 4700
          env:
            - name: NAME
              value: "auth"
            - name: PORT
              value: "4700"
            - name: HOST
              value: "http://auth-svc"
            - name: JWT_ACCESS_SECRET
              value: "defaultaccesssecret"
            - name: JWT_ACCESS_EXPIRES_IN
              value: "30m"
            - name: DISCOVERY_URL
              value: "http://discovery-svc"
            - name: DISCOVERY_PORT
              value: "4000"
