apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
spec:
  type: ClusterIP
  selector:
    app: discovery-app
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-app
  template:
    metadata:
      labels:
        app: discovery-app
    spec:
      containers:
        - name: discovery
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/discovery
          resources:
            limits:
              cpu: 0.5
              memory: "200Mi"
            requests:
              cpu: 0.5
              memory: "100Mi"            
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NAME
              value: "user"
            - name: PORT
              value: "4000"
