apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: ClusterIP
  selector:
    app: gateway-app
  ports:
    - port: 80
      targetPort: 4060
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 4060
          env:
            - name: PORT
              value: "4060"
            - name: URL_APPOINTMENT
              value: "http://appointment-svc/appointment"
            - name: URL_PATIENT
              value: "http://patient-svc/patient"
            - name: URL_AUTH
              value: "http://auth-svc/auth"
