apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
data:
  domain: https://dev-api.company.com
  apiUrl: /api/v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-python
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend 
    spec:
      containers:
        - name: app-python
          image: nginx:alpine
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: domain
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: apiUrl                  